apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-calc-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: vat-calc
  template:
    metadata:
      labels:
        app: vat-calc
    spec:
      containers:
        - name: vat-calc
          image: yash5090/vat-calc:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
